/* 
    1.	Employee Bonus Calculation	(20 Points)
Write a C++ program that calculates the yearly bonus for an employee based on their monthly salary and the number of years they’ve worked at the company. The bonus is calculated as 5% of the monthly salary multiplied by the number of years worked. The program should ask for the employee’s monthly salary and the number of years they’ve worked, then output the bonus amount.
Define the following variables:
•	monthlySalary: Holds the employee’s monthly salary.
•	yearsWorked: Holds the number of years the employee has worked.
•	bonus: Holds the calculated bonus amount.
*/

//	START
#include <iostream>
using namespace std;
int main() {
    double monthlySalary, bonus;
    int yearsWorked;
    cout << "This program calculates the yearly bonus for an employee based on their monthly salary and the number of years they’ve worked at the company." << endl;
    cout << "Enter the employee’s monthly salary: ";
    cin >> monthlySalary;
    cout << "Enter the number of years they’ve worked: ";
    cin >> yearsWorked;
    bonus = (monthlySalary * 0.05) * yearsWorked;
    cout << "The yearly bonus amount is: $" << bonus << endl;
    return 0;
}
//	END


/*

2.	Simple Store Revenue Calculator	(30 Points)
Write a C++ program that calculates the total revenue generated by a store. 
The program should prompt the user to enter the number of products sold, the price per product, and the sales tax rate (as a percentage). 
The program should then calculate the total revenue, including tax, and display the result.
Define the following variables:
•	productsSold: Holds the number of products sold.
•	pricePerProduct: Holds the price of each product.
•	salesTax: Holds the sales tax rate.
•	totalRevenue: Holds the total revenue including tax.

*/

#include <iostream>
using namespace std;

int main() {
    int productsSold;
    double pricePerProduct, salesTax, totalRevenue;
    cout << "This program calculates the total revenue generated by a store." << endl;
    cout << "Enter the number of products sold: ";
    cin >> productsSold;
    cout << "Enter the price per product: ";
    cin >> pricePerProduct;
    cout << "Enter the sales tax rate (as a percentage): ";
    cin >> salesTax;
    totalRevenue = (productsSold * pricePerProduct) * (1 + salesTax / 100);
    cout << "The total revenue generated by the store (including tax) is: $" << totalRevenue << endl;
    return 0;
}

/*

3.  Even or Odd Number Checker using if	(30 Points)
Write a C++ program that asks the user to enter an integer. 
The program should then determine if the number is even or odd using an if-else statement.
If the number is divisible by 2, it is even.
If the number is not divisible by 2, it is odd.
The program should output whether the number is even or odd.

*/

#include <iostream>
using namespace std;

int main() {
    int num;
    cout << "Enter an integer: ";
    cin >> num;
    if (num % 2 == 0) {
        cout << num << " is even." << endl;
    } else {
        cout << num << " is odd." << endl;
    }
}

